apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
data:
  glance.yml: |
    pages:
      - name: Home
        columns:
          - size: small
            widgets:
              - type: calendar

              - type: rss
                limit: 10
                collapse-after: 3
                cache: 3h
                feeds:
                  - url: https://stackoverflow.blog/feed/
                  - url: https://buttondown.email/cassidoo/rss
                  - url: https://github.com/readme.rss
                  - url: https://kerkour.com/feed.xml
            
          - size: full
            widgets:
              - type: search
                search-engine: duckduckgo
                bangs:
                  - title: Youtube
                    shortcut: "!yt"
                    url: https://www.youtube.com/results?search_query={QUERY}
                  - title: Nix Packages
                    shortcut: "!np"
                    url: https://search.nixos.org/packages?type=packages&channel=unstable&query={QUERY}

              - type: hacker-news

              - type: reddit
                subreddit: selfhosted

          - size: small
            widgets:
              - type: weather
                location: Campinas, Brazil

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Wakapi
                    url: http://192.168.0.13:31115
                  - title: Soft Git Server
                    url: http://192.168.0.13:23232

    theme:
      background-color: 50 1 6
      primary-color: 24 97 58
      negative-color: 209 88 54
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      containers:
        - name: glance
          image: glanceapp/glance
          ports:
            - containerPort: 8080
              name: glance-port
              protocol: TCP
          volumeMounts:
            - mountPath: /app/glance.yml
              name: glance-config
              subPath: glance.yml
          imagePullPolicy: IfNotPresent
      volumes:
        - name: glance-config
          configMap:
            name: glance-config
            items:
              - key: glance.yml
                path: glance.yml
---
apiVersion: v1
kind: Service
metadata:
  name: glance-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: glance
  ports:
    - name: glance-port
      port: 8080
      nodePort: 31111
