apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: paisa
  labels:
    app: paisa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paisa
  template:
    metadata:
      labels:
        app: paisa
    spec:
      containers:
      - image: ananthakumaran/paisa:latest
        imagePullPolicy: IfNotPresent
        name: paisa
        ports:
        - containerPort: 7500
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /root/Documents/paisa/
          name: paisa-data
  volumeClaimTemplates:
  - metadata:
      name: paisa-data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "1Mi"
      storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: paisa-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: paisa
  ports:
    - name: paisa-port
      port: 7500
      nodePort: 31112
