apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-volume
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/pedro-correa/data"
